repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: ''
    hooks:
      - id: clang-format

  - repo: local
    hooks:
      - id: build-check
        name: Build Check
        entry: bash -c "cmake -S . -B build && cmake --build build"
        language: system
